---
title: "React Routerでエラー画面の実装が簡単になっていたので実装"
emoji: "🌟"
type: "tech"
topics: []
published: false
---

こんばんわ✋、@nerusanです。

Webアプリケーションにおいて、ルーティング処理を行うのは、必須です。
ルーティングを実現するライブラリの一つとして、React Routerがあります。

https://reactrouter.com/en/main

React Routerのチュートリアルを見ていると、エラー処理が簡単に実装できることに気づいたので、共有としてまとめます。

以下がチュートリアルになります。
react-routerを使うことがある人はぜひ一通り実践してみてください！

https://reactrouter.com/en/main/start/tutorial

:::message
本記事では、React１８のSuspenseを利用を前提とした話を進めます。
:::

# 環境
今回紹介するコードでは、以下の環境で記述されています。

- React v18.2.0
- vite v3.1.0
- axios v1.2.0
- [@tanstack/react-query v4.18.0](https://tanstack.com/query/v4/?from=reactQueryV3&original=https://react-query-v3.tanstack.com/)
- @mui/material v5.11.0
- react-hook-form v7.39.6

# 作るもの

メールアドレス、名前、パスワードでユーザ登録を行う機能を考えます。

![](https://storage.googleapis.com/zenn-user-upload/167f54c61f87-20230105.png)

# これまでのエラーハンドリング
Suspenseを利用した際の、エラー画面は、react-error-boundaryを利用するのが一般的かなって思います。

https://github.com/bvaughn/react-error-boundary

react-error-boundaryが例外をキャッチし、エラー画面を表示するという流れになります。

react-error-boundaryを利用した実装例を以下に示します。ただ、こちらでは、分かりやすさを優先するため、ルーティング処理をしていません。

```ts:src/providers/app.tsx
import { queryClient } from "@/lib/react-query";
import {
  QueryClientProvider,
  QueryErrorResetBoundary,
} from "@tanstack/react-query";
import * as React from "react";
import { ErrorBoundary } from "react-error-boundary";

/**
 * エラー画面
 * @param param0
 * @returns
 */
const ErrorFallback = ({
  reset,
  error,
}: {
  reset: (...args: unknown[]) => void;
  error: Error;
}) => {
  return (
    <div role="alert">
      <h2>エラーが発生しました。</h2>
      <p>{error.message}</p>
      <button onClick={() => reset()}>ホームへ</button>
    </div>
  );
};

type AppProviderProps = {
  children: React.ReactNode;
};

/**
 * プロパイダー
 */
export const AppProvider = ({ children }: AppProviderProps) => {
  return (
    <QueryErrorResetBoundary>
      {({ reset }) => (
        <ErrorBoundary
          onReset={reset}
          fallbackRender={({ resetErrorBoundary, error }) => (
            <ErrorFallback reset={resetErrorBoundary} error={error} />
          )}
        >
          <React.Suspense fallback={<div>loading...</div>}>
            <QueryClientProvider client={queryClient}>
              {children}
            </QueryClientProvider>
          </React.Suspense>
        </ErrorBoundary>
      )}
    </QueryErrorResetBoundary>
  );
};
```

```ts:src/lib/react-query.ts
import { DefaultOptions, QueryClient } from "@tanstack/react-query";
import { AxiosError } from "axios";

const queryConfig: DefaultOptions<
  AxiosError<{ statusCode: number; title: string; message: string }>
> = {
  queries: {
    suspense: true,
    useErrorBoundary(error) {
      // 500エラーは例外エラーとしてキャッチさせる
      if (error.response) {
        return error.response?.status >= 500;
      }
      return true;
    },
    refetchOnWindowFocus: false,
    retry: false,
  },
  mutations: {
    useErrorBoundary(error) {
      // 500エラーは例外エラーとしてキャッチさせる
      if (error.response) {
        return error.response?.status >= 500;
      }
      return true;
    },
  },
};

export const queryClient = new QueryClient({
  defaultOptions: queryConfig as DefaultOptions,
});
```


```tsx:src/pages/Signup.tsx
import {
  ERR_MAIL_FORMAT_MESSAGE,
  ERR_REQUIRE_MESSAGE,
  MAIL_FORMAT_REGEXP,
} from "@/const/const";
import { LoadingButton } from "@mui/lab";
import { Box, TextField } from "@mui/material";
import { useMutation } from "@tanstack/react-query";
import { AxiosError } from "axios";
import React from "react";
import { useForm } from "react-hook-form";
import {
  registerWithEmailAndPassword,
  RegisterCredentialsDTO,
} from "../api/register";

/**
 * サインアップ機能
 */
export const Signup: React.FC = React.memo(() => {
  const [userId, setUserId] = React.useState<string>("");
  const {
    register,
    handleSubmit,
    getValues,
    setError,
    formState: { errors },
  } = useForm({
    defaultValues: {
      email: "",
      familyName: "",
      familyNameKana: "",
      firstName: "",
      firstNameKana: "",
      password: "",
    },
  });

  const { mutate, isLoading } = useMutation(
    (data: RegisterCredentialsDTO) =>
      registerWithEmailAndPassword(data),
    {
      onSuccess: (res) => {
        setUserId(res.data.data.userId);
      },
      onError: (
        err: AxiosError<{ statusCode: number; title: string; message: string }>
      ) => {
        if (err.response?.status === 409) {
          setError("email", { message: err.response.data.message });
          return;
        }
      },
    }
  );

  return (
    <Box className="App" mx="auto" maxWidth="400px">
      <h2>
        <Box textAlign="center">アカウント新規登録</Box>
      </h2>
      <form onSubmit={handleSubmit((data) => mutate(data))}>
        <Box marginBottom="24px">
          <Box mb="4px">メールアドレス</Box>
          <TextField
            fullWidth
            placeholder="yamada.taro@example.com"
            variant="outlined"
            type="email"
            {...register("email", {
              required: { value: true, message: ERR_REQUIRE_MESSAGE },
              pattern: {
                value: MAIL_FORMAT_REGEXP,
                message: ERR_MAIL_FORMAT_MESSAGE,
              },
            })}
          />
          <Box sx={{ color: "error.main" }}>{errors.email?.message}</Box>
        </Box>
        <Box marginBottom="24px">
          <Box mb="4px">姓（全角）</Box>
          <TextField
            fullWidth
            placeholder="山田"
            type="text"
            variant="outlined"
            {...register("familyName", {
              required: { value: true, message: ERR_REQUIRE_MESSAGE },
            })}
          />
          <Box sx={{ color: "error.main" }}>{errors.familyName?.message}</Box>
        </Box>
        <Box marginBottom="24px">
          <Box mb="4px">名（全角）</Box>
          <TextField
            fullWidth
            placeholder="太郎"
            type="text"
            variant="outlined"
            {...register("familyNameKana", {
              required: { value: true, message: ERR_REQUIRE_MESSAGE },
            })}
          />
          <Box sx={{ color: "error.main" }}>
            {errors.familyNameKana?.message}
          </Box>
        </Box>
        <Box marginBottom="24px">
          <Box mb="4px">姓カナ（全角）</Box>
          <TextField
            fullWidth
            placeholder="ヤマダ"
            type="text"
            variant="outlined"
            {...register("firstName", {
              required: { value: true, message: ERR_REQUIRE_MESSAGE },
            })}
          />
          <Box sx={{ color: "error.main" }}>{errors.firstName?.message}</Box>
        </Box>
        <Box marginBottom="24px">
          <Box mb="4px">名カナ（全角）</Box>
          <TextField
            fullWidth
            type="text"
            placeholder="タロウ"
            variant="outlined"
            {...register("firstNameKana", {
              required: { value: true, message: ERR_REQUIRE_MESSAGE },
            })}
          />
          <Box sx={{ color: "error.main" }}>
            {errors.firstNameKana?.message}
          </Box>
        </Box>
        <Box marginBottom="24px">
          <Box mb="4px">パスワード</Box>
          <TextField
            fullWidth
            type="password"
            variant="outlined"
            {...register("password", {
              required: { value: true, message: ERR_REQUIRE_MESSAGE },
            })}
          />
          <Box sx={{ color: "error.main" }}>{errors.password?.message}</Box>
        </Box>
        <LoadingButton
          size="large"
          fullWidth
          sx={{ marginTop: "50px" }}
          variant="contained"
          type="submit"
          color="primary"
          loading={isLoading}
        >
          登録
        </LoadingButton>
	{userId && <p>ユーザIDは{userId}です。</p>}
      </form>
    </Box>
  );
});
```

ここでのポイントは、2点です。

1点目は、例外をキャッチしたいJSXを`ErrorBoudnary`コンポーネントで括ります。
今回は、`src/providers/app.tsx`で アプリケーション全体を括ります。
子コンポーネントで例外が発生したら、例外をキャッチして、`fallbackRender`に指定されたコンポーネントがエラー画面として表示されます。

また、クエリで suspense や useErrorBoundaries を使用する場合、何らかのエラーが発生した後に再描画する際にクエリに再試行することを知らせる方法が必要になります。

クエリのエラーは、`QueryErrorResetBoundary` コンポーネントあるいは useQueryErrorResetBoundary フックでリセットすることができます。

詳しくは以下のページを参考にしてください。

https://tanstack.com/query/v4/docs/react/guides/suspense#resetting-error-boundaries

今回は、`QueryErrorResetBoundary`コンポーネントを利用しています。

2点目は、@tanstack/react-qeuryでerror-boundaryの利用を設定します。
`src/lib/react-query.ts`にてグローバルに設定をしています。

queriesとmutationsそれぞれに対して、`useErrorBoundary`をtrueにすると設定できます。
ここでは、ステータスコード500番台以上のエラーのみエラー画面を表示するように設定しています。

今回の例だと、登録済みのメールアドレスで登録しようとする場合、409が返却されますが、この時、エラー画面に遷移したくありません。
遷移すると、再度メールアドレスを入力してもらうことができないためです。（リロードしたらいけますが、名前も入力し直しになるため、めんどくさいです。）

▼エラー画面に遷移すると再度メールアドレス入力できない❌
![](https://storage.googleapis.com/zenn-user-upload/e4e0959ec22f-20230104.png)

▼エラー画面に遷移させず再度メールアドレス入力できるようにする⭕️
![](https://storage.googleapis.com/zenn-user-upload/7c24c1465309-20230104.png)


# React Routerを利用した場合

次に、React Routerを利用した方法を紹介します。


```tsx:src/providers/app.tsx
import { AuthProvider } from "@/lib/auth";
import { queryClient } from "@/lib/react-query";
import { getAppRoutes } from "@/routes";
import {
  Box,
  CircularProgress,
  createTheme,
  ThemeProvider,
} from "@mui/material";
import { QueryClientProvider } from "@tanstack/react-query";
import * as React from "react";
import { RouterProvider } from "react-router-dom";
import { RecoilRoot } from "recoil";

type AppProviderProps = {
  children?: React.ReactNode;
};

/**
 * プロパイダー
 */
export const AppProvider = ({ children }: AppProviderProps) => {
  const theme = createTheme({});
  return (
    <RecoilRoot>
      <React.Suspense
        fallback={
          <Box
            display="flex"
            alignItems="center"
            justifyContent="center"
            height="100vh"
          >
            <CircularProgress />
          </Box>
        }se
      >
        <QueryClientProvider client={queryClient}>
          <AuthProvider>
            <ThemeProvider theme={theme}>
              <RouterProvider router={getAppRoutes()} />
            </ThemeProvider>
          </AuthProvider>
        </QueryClientProvider>
      </React.Suspense>
    </RecoilRoot>
  );
};
```

```tsx:src/routes/index.tsx
import { Error } from "@/components/Error";
import { createBrowserRouter, redirect, RouteObject } from "react-router-dom";
import { publicRoutes } from "./public";
const { SignupPage } = lazyImport(() => import("@/pages/Signup"), "SignupPage");

/**
 * ログインしていない時でもみれるページ一覧
 */
export const publicRoutes: RouteObject[] = [
  {
    path: "/",
    element: <Layout />,
    errorElement: <Error />,
    children: [{ path: "/signup", element: <SignupPage /> }],
  },
];

/**
 * 全体のルーティングの設定
 */
export const getAppRoutes = () => {
  const commonRoutes: RouteObject[] = [
    {
      path: "/",
      errorElement: (
        <Error
          title="404"
          message="このページはすでに削除されているか、URLが間違っている可能性があります。"
        />
      ),
    },
  ];

  const routes = publicRoutes;
  const root = createBrowserRouter([...commonRoutes, ...routes]);
  return root;
};
```

```tsx:src/components/Error.tsx
import { Box, Button } from "@mui/material";
import { useQueryErrorResetBoundary } from "@tanstack/react-query";
import { AxiosError } from "axios";
import { useRouteError } from "react-router-dom";

type Props = {
  title?: string;
  message?: string;
};

/**
 * エラー画面
 * @param param0
 * @returns
 */
export const Error = ({ title, message }: Props) => {
  // エラーが発生した時の情報を取得する
  const error = useRouteError() as AxiosError<{
    statusCode: number;
    title: string;
    message: string;
  }>;
  const { reset } = useQueryErrorResetBoundary();

  return (
    <Box
      role="alert"
      display="flex"
      alignItems="center"
      justifyContent="center"
      height="100vh"
      flexDirection="column"
    >
      <h1>
        {title || error.response?.data.title || "エラーが発生しました。"}
      </h1>
      <p>{message || error.response?.data.message || error.message}</p>
      <Button
        variant="outlined"
        onClick={() => {
          reset();
          window.location.assign(window.location.origin);
        }}
      >
        ホームへ
      </Button>
    </Box>
  );
};
```

`src/pages/Signup.tsx`、`src/lib/react-query.ts`はreact-error-boundaryの時と同じです。500番台の場合のみエラー画面を出します。

プロバイダー(`src/providers/app.tsx`)でルーティングの設定は加えていますが、例外キャッチのため別途子コンポーネントを括る必要がなくなったため、すっきりしました。

エラーの設定をしているのは、ルーティングを設定している`src/routes/index.tsx`になります。配下のページ(elemnentに指定したコンポーネント)、または、ローダー、アクションでなにか例外が発生したら、`errorElement`に指定したコンポーネントがエラー画面として表示されます。

```tsx:
  const commonRoutes: RouteObject[] = [
    {
      path: "/signup",
      element: <Signup />, // 1
      loader: loaderFn,    // 2
      action: actionFn,    // 3
      errorElement: (      // 1, 2, 3のいずれかで例外が発生したら、errorElementに指定されたエラー画面を表示 
        <Error />
      ),
    },
  ];
```

発生したエラーについての情報は、`useRouteError`を利用することで、取得できます。
`src/components/Error.tsx`は実際に表示するエラー画面コンポーネントです。エラー情報は、propsからも指定することができるようにしています。

また、ルート`/`に対して`errorElemnt`を指定することで、存在しないページにアクセスするとエラー画面が表示されます。

▼存在しない`/signhoge`にアクセス
![](https://storage.googleapis.com/zenn-user-upload/00949de79e4d-20230105.png)

▼500エラーもしっかり表示される
![](https://storage.googleapis.com/zenn-user-upload/931e6d1e7c6d-20230105.png)

# まとめ
いかがでしたか。
他にも、ログイン状況に応じたリダイレクト処理(ログイン状態出なければ、`/login`に飛ばすなど)なども簡単に実装ができそう。

また、




